### PR TITLE
Control for multiple choice display language

### PR DESCRIPTION
**Pull request by mooncake4132**
I'm looking for some way to change the display language of the multiple choice options. Are you okay with reusing the "Prefer English titles when available" option or do you think it's better to have another option since Japanese romaji is not really English?

### CODE REVIEW

**Comment by mertvn** [comment]
Do you just want support for displaying Japanese titles, or do you need other languages as well? If you do need non-Japanese languages, you should be aware that we have very few of them in the database because we only fetch titles for official releases. 

Either way, this is not the right way to implement this feature for the reason you've mentioned.

**Comment by mertvn** [comment]
Actually I just realized that supporting other languages would need changes in the backend as well, which I don't think is worth it at the time. So you should just create a new option along the lines of "Use raw Japanese titles for multiple choice options" if you want to add this.

**Comment by mooncake4132** [comment]
Makes sense. I added a new option for preferring the original language for multiple choice options. Let me know if you want to tweak the naming of anything.

**Comment by mertvn** [comment]
Thanks for the contribution.

**Pull request merged**
